CREATE TABLE [dbo].[Cards]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [CardNumber] NVARCHAR(19) NOT NULL, 
    [CardHolder] NVARCHAR(100) NOT NULL, 
    [ExpiryMonth] NVARCHAR(2) NOT NULL, 
    [ExpiryYear] NVARCHAR(2) NOT NULL,
    [CardId] AS 'CRD' + RIGHT('0000000000000000000' + CAST(ID AS NVARCHAR(19)), 19) PERSISTED NOT NULL
)
