USE [master]
GO

/****** Object:  Database [checkout]    Script Date: 20/10/2022 10:03:59 ******/
CREATE DATABASE [checkout]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'checkout', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\checkout.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'checkout_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\checkout_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [checkout] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [checkout].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [checkout] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [checkout] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [checkout] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [checkout] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [checkout] SET ARITHABORT OFF 
GO

ALTER DATABASE [checkout] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [checkout] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [checkout] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [checkout] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [checkout] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [checkout] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [checkout] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [checkout] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [checkout] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [checkout] SET  DISABLE_BROKER 
GO

ALTER DATABASE [checkout] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [checkout] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [checkout] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [checkout] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [checkout] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [checkout] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [checkout] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [checkout] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [checkout] SET  MULTI_USER 
GO

ALTER DATABASE [checkout] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [checkout] SET DB_CHAINING OFF 
GO

ALTER DATABASE [checkout] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [checkout] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [checkout] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [checkout] SET QUERY_STORE = OFF
GO

ALTER DATABASE [checkout] SET  READ_WRITE 
GO


